- hosts: localhost
  become: true
  gather_facts: yes
  vars_files:
    - ../vars/all.yaml
  tasks:
    - name: Find all files containing sosreport
      find:
        paths: "~/"
        patterns: "sosreport"
      register: sosreportfiles

    - name: Remove local sosreport folder
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ sosreportfiles }}"


- hosts: sosreport_machines
  become: true
  gather_facts: yes

  vars_files:
    - ../vars/all.yaml

  tasks:
    - name: Collect sosreport
      import_role:
        name: sosreport

- hosts: localhost
  become: true
  gather_facts: yes

  vars_files:
    - ../vars/all.yaml

  tasks:
    - name: Make a tar from the sosreport folder
      community.general.archive:
        path: "{{ sosreport_local_dir }}"
        dest: "~/{{ sosreport_case }}_{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-sosreport.gz"
        format: gz
        force_archive: true
        remove: yes
        

